### ISSUE TITLE
Configurable Drawer Opening Direction

### ISSUE THREAD

**Issue by theetherGit** [huntabyte/vaul-svelte#37] opened 2024-01-27 06:34 UTC
### Feature

As new version of Vaul React have new direction prop for drawer, we can add that from https://github.com/emilkowalski/vaul/pull/187.

I can work on this if you allow.

### Relevent

https://github.com/emilkowalski/vaul/pull/187 - Pull Request for direction functionality in drawer.

> It got duplicated by mistake, I had this written yesterday.

**Comment by huntabyte** [comment] 2024-01-27 21:10
Duplicate of #36

**Closed by huntabyte** 2024-01-27 21:10 UTC
